/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminScriptsRouteImport } from './routes/admin.scripts'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AgentAssistantRouteImport } from './routes/agent.assistant'
import { Route as AgentDashboardRouteImport } from './routes/agent.dashboard'
import { Route as AgentFollowUpsRouteImport } from './routes/agent.follow-ups'
import { Route as AgentMarketingRouteImport } from './routes/agent.marketing'
import { Route as AgentMessagesRouteImport } from './routes/agent.messages'
import { Route as AgentPerformanceRouteImport } from './routes/agent.performance'
import { Route as AgentProfileRouteImport } from './routes/agent.profile'
import { Route as AgentScriptsRouteImport } from './routes/agent.scripts'
import { Route as AgentServicesRouteImport } from './routes/agent.services'
import { Route as AgentTeamRouteImport } from './routes/agent.team'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin.agents.index'
import { Route as AdminAgentsIdRouteImport } from './routes/admin.agents.$id'
import { Route as AgentAcademyIndexRouteImport } from './routes/agent.academy.index'
import { Route as AgentAcademyLessonIdRouteImport } from './routes/agent.academy.$lessonId'
import { Route as AgentLeadsIndexRouteImport } from './routes/agent.leads.index'
import { Route as AgentLeadsIdRouteImport } from './routes/agent.leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScriptsRoute = AdminScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AgentAssistantRoute = AgentAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AgentRoute,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgentRoute,
} as any)
const AgentFollowUpsRoute = AgentFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMarketingRoute = AgentMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMessagesRoute = AgentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AgentRoute,
} as any)
const AgentPerformanceRoute = AgentPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AgentRoute,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentRoute,
} as any)
const AgentScriptsRoute = AgentScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AgentRoute,
} as any)
const AgentServicesRoute = AgentServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AgentRoute,
} as any)
const AgentTeamRoute = AgentTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AgentRoute,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsIdRoute = AdminAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AgentAcademyIndexRoute = AgentAcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAcademyLessonIdRoute = AgentAcademyLessonIdRouteImport.update({
  id: '/academy/$lessonId',
  path: '/academy/$lessonId',
  getParentRoute: () => AgentRoute,
} as any)
const AgentLeadsIndexRoute = AgentLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AgentRoute,
} as any)
const AgentLeadsIdRoute = AgentLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/agent/assistant': typeof AgentAssistantRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/follow-ups': typeof AgentFollowUpsRoute
  '/agent/marketing': typeof AgentMarketingRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/performance': typeof AgentPerformanceRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/scripts': typeof AgentScriptsRoute
  '/agent/services': typeof AgentServicesRoute
  '/agent/team': typeof AgentTeamRoute
  '/admin/agents/$id': typeof AdminAgentsIdRoute
  '/agent/academy/$lessonId': typeof AgentAcademyLessonIdRoute
  '/agent/leads/$id': typeof AgentLeadsIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/agent/academy/': typeof AgentAcademyIndexRoute
  '/agent/leads/': typeof AgentLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/agent/assistant': typeof AgentAssistantRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/follow-ups': typeof AgentFollowUpsRoute
  '/agent/marketing': typeof AgentMarketingRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/performance': typeof AgentPerformanceRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/scripts': typeof AgentScriptsRoute
  '/agent/services': typeof AgentServicesRoute
  '/agent/team': typeof AgentTeamRoute
  '/admin/agents/$id': typeof AdminAgentsIdRoute
  '/agent/academy/$lessonId': typeof AgentAcademyLessonIdRoute
  '/agent/leads/$id': typeof AgentLeadsIdRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/agent/academy': typeof AgentAcademyIndexRoute
  '/agent/leads': typeof AgentLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/agent/assistant': typeof AgentAssistantRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/follow-ups': typeof AgentFollowUpsRoute
  '/agent/marketing': typeof AgentMarketingRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/performance': typeof AgentPerformanceRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/scripts': typeof AgentScriptsRoute
  '/agent/services': typeof AgentServicesRoute
  '/agent/team': typeof AgentTeamRoute
  '/admin/agents/$id': typeof AdminAgentsIdRoute
  '/agent/academy/$lessonId': typeof AgentAcademyLessonIdRoute
  '/agent/leads/$id': typeof AgentLeadsIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/agent/academy/': typeof AgentAcademyIndexRoute
  '/agent/leads/': typeof AgentLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/login'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/scripts'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/teams'
    | '/agent/assistant'
    | '/agent/dashboard'
    | '/agent/follow-ups'
    | '/agent/marketing'
    | '/agent/messages'
    | '/agent/performance'
    | '/agent/profile'
    | '/agent/scripts'
    | '/agent/services'
    | '/agent/team'
    | '/admin/agents/$id'
    | '/agent/academy/$lessonId'
    | '/agent/leads/$id'
    | '/admin/agents/'
    | '/agent/academy/'
    | '/agent/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/login'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/scripts'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/teams'
    | '/agent/assistant'
    | '/agent/dashboard'
    | '/agent/follow-ups'
    | '/agent/marketing'
    | '/agent/messages'
    | '/agent/performance'
    | '/agent/profile'
    | '/agent/scripts'
    | '/agent/services'
    | '/agent/team'
    | '/admin/agents/$id'
    | '/agent/academy/$lessonId'
    | '/agent/leads/$id'
    | '/admin/agents'
    | '/agent/academy'
    | '/agent/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/login'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/scripts'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/teams'
    | '/agent/assistant'
    | '/agent/dashboard'
    | '/agent/follow-ups'
    | '/agent/marketing'
    | '/agent/messages'
    | '/agent/performance'
    | '/agent/profile'
    | '/agent/scripts'
    | '/agent/services'
    | '/agent/team'
    | '/admin/agents/$id'
    | '/agent/academy/$lessonId'
    | '/agent/leads/$id'
    | '/admin/agents/'
    | '/agent/academy/'
    | '/agent/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scripts': {
      id: '/admin/scripts'
      path: '/scripts'
      fullPath: '/admin/scripts'
      preLoaderRoute: typeof AdminScriptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agent/assistant': {
      id: '/agent/assistant'
      path: '/assistant'
      fullPath: '/agent/assistant'
      preLoaderRoute: typeof AgentAssistantRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/follow-ups': {
      id: '/agent/follow-ups'
      path: '/follow-ups'
      fullPath: '/agent/follow-ups'
      preLoaderRoute: typeof AgentFollowUpsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/marketing': {
      id: '/agent/marketing'
      path: '/marketing'
      fullPath: '/agent/marketing'
      preLoaderRoute: typeof AgentMarketingRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/messages': {
      id: '/agent/messages'
      path: '/messages'
      fullPath: '/agent/messages'
      preLoaderRoute: typeof AgentMessagesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/performance': {
      id: '/agent/performance'
      path: '/performance'
      fullPath: '/agent/performance'
      preLoaderRoute: typeof AgentPerformanceRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/scripts': {
      id: '/agent/scripts'
      path: '/scripts'
      fullPath: '/agent/scripts'
      preLoaderRoute: typeof AgentScriptsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/services': {
      id: '/agent/services'
      path: '/services'
      fullPath: '/agent/services'
      preLoaderRoute: typeof AgentServicesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/team': {
      id: '/agent/team'
      path: '/team'
      fullPath: '/agent/team'
      preLoaderRoute: typeof AgentTeamRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/$id': {
      id: '/admin/agents/$id'
      path: '/agents/$id'
      fullPath: '/admin/agents/$id'
      preLoaderRoute: typeof AdminAgentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agent/academy/': {
      id: '/agent/academy/'
      path: '/academy'
      fullPath: '/agent/academy/'
      preLoaderRoute: typeof AgentAcademyIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/academy/$lessonId': {
      id: '/agent/academy/$lessonId'
      path: '/academy/$lessonId'
      fullPath: '/agent/academy/$lessonId'
      preLoaderRoute: typeof AgentAcademyLessonIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/leads/': {
      id: '/agent/leads/'
      path: '/leads'
      fullPath: '/agent/leads/'
      preLoaderRoute: typeof AgentLeadsIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/leads/$id': {
      id: '/agent/leads/$id'
      path: '/leads/$id'
      fullPath: '/agent/leads/$id'
      preLoaderRoute: typeof AgentLeadsIdRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScriptsRoute: typeof AdminScriptsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminAgentsIdRoute: typeof AdminAgentsIdRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScriptsRoute: AdminScriptsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminAgentsIdRoute: AdminAgentsIdRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentAssistantRoute: typeof AgentAssistantRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentFollowUpsRoute: typeof AgentFollowUpsRoute
  AgentMarketingRoute: typeof AgentMarketingRoute
  AgentMessagesRoute: typeof AgentMessagesRoute
  AgentPerformanceRoute: typeof AgentPerformanceRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentScriptsRoute: typeof AgentScriptsRoute
  AgentServicesRoute: typeof AgentServicesRoute
  AgentTeamRoute: typeof AgentTeamRoute
  AgentAcademyLessonIdRoute: typeof AgentAcademyLessonIdRoute
  AgentLeadsIdRoute: typeof AgentLeadsIdRoute
  AgentAcademyIndexRoute: typeof AgentAcademyIndexRoute
  AgentLeadsIndexRoute: typeof AgentLeadsIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAssistantRoute: AgentAssistantRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentFollowUpsRoute: AgentFollowUpsRoute,
  AgentMarketingRoute: AgentMarketingRoute,
  AgentMessagesRoute: AgentMessagesRoute,
  AgentPerformanceRoute: AgentPerformanceRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentScriptsRoute: AgentScriptsRoute,
  AgentServicesRoute: AgentServicesRoute,
  AgentTeamRoute: AgentTeamRoute,
  AgentAcademyLessonIdRoute: AgentAcademyLessonIdRoute,
  AgentLeadsIdRoute: AgentLeadsIdRoute,
  AgentAcademyIndexRoute: AgentAcademyIndexRoute,
  AgentLeadsIndexRoute: AgentLeadsIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
