// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfysnkkzesbovtnmoccb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeXNua2t6ZXNib3Z0bm1vY2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzg2NjcsImV4cCI6MjA2NzcxNDY2N30.a7oWYYvQtQtyiRX4bSFEOsqJyEbmOiP_3V3EKFXxMKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});